"""Add DetectionLog

Revision ID: f46a979ec2f8
Revises: 4fd961b3663a
Create Date: 2026-02-07 10:47:47.823384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f46a979ec2f8'
down_revision = '4fd961b3663a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detection_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('camera_id', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('speed_inference', sa.Float(), nullable=True),
    sa.Column('speed_fps', sa.Float(), nullable=True),
    sa.Column('has_detections', sa.Boolean(), nullable=True),
    sa.Column('detection_count', sa.Integer(), nullable=True),
    sa.Column('detections', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_logs_camera_id'), 'detection_logs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_detection_logs_has_detections'), 'detection_logs', ['has_detections'], unique=False)
    op.create_index(op.f('ix_detection_logs_id'), 'detection_logs', ['id'], unique=False)
    op.create_index(op.f('ix_detection_logs_model_id'), 'detection_logs', ['model_id'], unique=False)
    op.create_index(op.f('ix_detection_logs_timestamp'), 'detection_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_logs_timestamp'), table_name='detection_logs')
    op.drop_index(op.f('ix_detection_logs_model_id'), table_name='detection_logs')
    op.drop_index(op.f('ix_detection_logs_id'), table_name='detection_logs')
    op.drop_index(op.f('ix_detection_logs_has_detections'), table_name='detection_logs')
    op.drop_index(op.f('ix_detection_logs_camera_id'), table_name='detection_logs')
    op.drop_table('detection_logs')
    # ### end Alembic commands ###
